name: 'new_project'
description: ''
publish_to: 'none'
version: '0.0.1+1'
environment: 
  sdk: '>=2.17.6 <3.0.0'
dependencies: 
  flutter: 
    sdk: 'flutter'
  cupertino_icons: '^1.0.2'
  flutter_localizations: 
    sdk: 'flutter'
  shindenshin: '^0.3.1'
  dio: '^4.0.6'
  bloc: '^8.1.0'
  flutter_bloc: '^8.0.1'
  hive_flutter: '^1.1.0'
  sentry_flutter: '^6.9.0'
  freezed_annotation: '^2.1.0'
  json_annotation: '^4.6.0'
  intl: '^0.17.0'
dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'
  flutter_lints: '^2.0.0'
  build_runner: '^2.2.0'
  freezed: '^2.1.0+1'
  json_serializable: '^6.3.1'
  dart_code_metrics: '^4.17.0'
  hive_generator: '^1.1.3'
  flutter_launcher_icons: '^0.10.0'
flutter_icons: 
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/app_icon.png'
flutter: 
  uses-material-design: true
