name: flutter_starter_cli
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  path: ^1.8.2
  yaml: ^3.1.1
  yaml_writer: ^1.0.2
  dio: ^4.0.6
  recase: ^4.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
